version: '3'
services:
  postgresql:
    image: postgres:12.2-alpine
    container_name: modhand-pg-dev
    environment:
      - APPLICATION=modhand
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_USER=modhand
      - POSTGRES_DB=modhand
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./dumps:/var/lib/postgresql/dumps
