version: '3'
services:
  postgresql:
    image: postgres:12.2-alpine
    container_name: modhand-pg-dev
    environment:
      - APPLICATION=modhand
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_USER=modhand
      - POSTGRES_DB=modhand
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  module-handbook-rails:
    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/module-handbook
      - /module-handbook/node_modules
    ports:
      - "3000:3000"
    environment:
      - RAILS_DB_HOST=postgresql
    depends_on:
      - postgresql
