
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: modhand
  password: modhand
  database: modhand
  port: 5433

test:
  <<: *default
  database: db/test.sqlite3

production:
  #     url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: module_handbook_production
  username: module_handbook
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
