default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: modhand
  password: modhand
  port: 5433

development:
  <<: *default
  database: modhand

test:
  <<: *default
  database: modhand-test

production:
  #     url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: module_handbook_production
  username: module_handbook
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
