name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      RAILS_DB_HOST: postgresql
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:12.2-alpine
        ports:
          - 5433:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
